# ____  _             _           
#|  _ \| |_   _  __ _(_)_ __  ___ 
#| |_) | | | | |/ _` | | '_ \/ __|
#|  __/| | |_| | (_| | | | | \__ \
#|_|   |_|\__,_|\__, |_|_| |_|___/
#               |___/             


# Updating Plugins
exec-once = hyprpm update

# Hyprwinwarp, For Custom Audio/Video Backgrounds
exec-once = hyprpm enable hyprwinwrap
# hycov
exec-once = hyprpm enable hycov
# hyev
exec-once = hyprpm enable hyev
# hych
# plugin = /usr/lib/libhych.so  

# Reloading Plugins
exec-once = hyprpm reload

# Hyprwinwrap
bind = SUPERSHIFTALT, B, exec, ~/.config/hypr/scripts/toggle-cava-bg
# Hyprcov
bind = Alt,tab,hycov:toggleoverview


bind=ALT,left,hycov:movefocus,l
bind=ALT,right,hycov:movefocus,r
bind=ALT,up,hycov:movefocus,u
bind=ALT,down,hycov:movefocus,d
