#           _           _                            _
# __      _(_)_ __   __| | _____      __  _ __ _   _| | ___  ___
# \ \ /\ / / | '_ \ / _` |/ _ \ \ /\ / / | '__| | | | |/ _ \/ __|
#  \ V  V /| | | | | (_| | (_) \ V  V /  | |  | |_| | |  __/\__ \
#   \_/\_/ |_|_| |_|\__,_|\___/ \_/\_/   |_|   \__,_|_|\___||___/

rules {
  windowrule = workspace 1, alacritty
  windowrule = workspace 2, firefox
  windowrule = workspace 3, kate
  windowrule = workspace 3, geany
  windowrule = workspace 4, pcmanfm-qt
  windowrule = workspace 4, title:^(ranger)$
  windowrule = workspace 5, rhythmbox
  windowrule = workspace 5, cantata
  windowrule = workspace 5, title:^(ncmpcpp)$
  windowrule = workspace 6, mpv
  windowrule = workspace 7, discord
  windowrule = workspace 9, title:^(htop)$
  windowrule = workspace 9, title:^(bashtop)$
}
